services:
  postgres:
    image: postgres:16-alpine
    container_name: posts_db
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: otavio
      POSTGRES_PASSWORD: olimpio
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: