spring.application.name=posts-sync-api

# Ligacao ao PostgreSQL via Docker (Porta 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/posts_db
spring.datasource.username=otavio
spring.datasource.password=olimpio
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes de Persistencia (JPA / Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true